service: serverless-todo-app

org: learning001
app: serverless-todo

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true

provider:
  name: aws
  runtime: nodejs22.x
  versionFunctions: true
  stage: staging
  region: ap-south-1
  environment:
    TODOS_TABLE: ${self:service}-todos-${sls:stage}
    API_VERSION: v1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - !GetAtt TodosTable.Arn

functions:
  createTodo:
    handler: src/handlers/v1/createTodo.handler
    description: "v1 - Create a new todo"
    events:
      - http:
          path: v1/todos
          method: post
          cors: true

  getTodos:
    handler: src/handlers/v1/getTodos.handler
    description: "v1 - Get all todos"
    events:
      - http:
          path: v1/todos
          method: get
          cors: true

  getTodo:
    handler: src/handlers/v1/getTodos.handler
    description: "v1 - Get single todo"
    events:
      - http:
          path: v1/todos/{id}
          method: get
          cors: true

  updateTodo:
    handler: src/handlers/v1/updateTodo.handler
    description: "v1 - Update a todo"
    events:
      - http:
          path: v1/todos/{id}
          method: put
          cors: true

  deleteTodo:
    handler: src/handlers/v1/deleteTodo.handler
    description: "v1 - Delete a todo"
    events:
      - http:
          path: v1/todos/{id}
          method: delete
          cors: true

resources:
  Resources:
    TodosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: todoId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST